language: node_js

node_js:
  - "10"

branches:
  only:
    - master
    - develop

cache:
  directories:
    - node_modules
    - $HOME/.local

install:
  - npm install

script:
  - echo "No tests ran"
