version: "3"

services:
  troposphere:
    image: the-leeds-repo/admin/troposphere
    build:
      context: ./docker/troposphere
      dockerfile: Dockerfile
    volumes:
      - ./aws:/tmp
    command: "python ${CFN_TEMPLATE}.py"
