#!/usr/bin/env bash

# Requires the following environment variables:
# $TRAVIS_BRANCH = The branch the build is against.

# Bail out on first error.
set -e

# Get the .env file.
echo "Downloading .env file..."
rm -f .env
aws secretsmanager get-secret-value \
    --secret-id env-admin | \
    python -c "import json,sys;obj=json.load(sys.stdin);print obj['SecretString'];" > .env

# Build.
echo "Building..."
npm run build

# Deploy to S3.
echo "Deploying..."
# node_modules/.bin/vue-cli-service s3-deploy
